spring:
  profiles:
    active: prod
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: never
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.sql: INFO
    org.springframework.data: INFO
    com.example.newsforeveryone : INFO

newsforeveryone:
  storage:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}

# naver API 기사 인증 정보
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
