spring:
  profiles:
    active: dev
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: never
  batch:
    job:
      enabled: true
      # names: rssJob, naverJob
    jdbc:
      initialize-schema: always


logging:
  level:
    org :
      hibernate.sql: DEBUG
      springframework.data: DEBUG
    com.example.newsforeveryone : INFO

# naver API 기사 인증 정보
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}