ALTER SEQUENCE article_backup_history_id_seq INCREMENT BY 50;
ALTER SEQUENCE comment_id_seq INCREMENT BY 50;
ALTER SEQUENCE interest_id_seq INCREMENT BY 50;
ALTER SEQUENCE keyword_id_seq INCREMENT BY 50;
ALTER SEQUENCE news_article_id_seq INCREMENT BY 50;
ALTER SEQUENCE notification_id_seq INCREMENT BY 50;
ALTER SEQUENCE source_id_seq INCREMENT BY 50;
ALTER SEQUENCE users_id_seq INCREMENT BY 50;